var hierarchy =
[
    [ "Clock", "classcrpropa_1_1Clock.html", null ],
    [ "LensPart", "classcrpropa_1_1LensPart.html", null ],
    [ "MagneticLens", "classcrpropa_1_1MagneticLens.html", null ],
    [ "ParticleMapsContainer", "classcrpropa_1_1ParticleMapsContainer.html", null ],
    [ "ParticleState", "classcrpropa_1_1ParticleState.html", null ],
    [ "Pixelization", "classcrpropa_1_1Pixelization.html", null ],
    [ "Random", "classcrpropa_1_1Random.html", null ],
    [ "ref_ptr< T >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::Candidate >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::Grid >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::MagneticField >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::Module >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::ModuleList >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::ObserverFeature >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::Source >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< crpropa::SourceFeature >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "ref_ptr< Module >", "classcrpropa_1_1ref__ptr.html", null ],
    [ "Referenced", "classcrpropa_1_1Referenced.html", [
      [ "Candidate", "classcrpropa_1_1Candidate.html", null ],
      [ "Grid< T >", "classcrpropa_1_1Grid.html", null ],
      [ "MagneticField", "classcrpropa_1_1MagneticField.html", [
        [ "JF12Field", "classcrpropa_1_1JF12Field.html", null ],
        [ "LogarithmicSpiralField", "classcrpropa_1_1LogarithmicSpiralField.html", null ],
        [ "MagneticFieldEvolution", "classcrpropa_1_1MagneticFieldEvolution.html", null ],
        [ "MagneticFieldGrid", "classcrpropa_1_1MagneticFieldGrid.html", null ],
        [ "MagneticFieldList", "classcrpropa_1_1MagneticFieldList.html", null ],
        [ "ModulatedMagneticFieldGrid", "classcrpropa_1_1ModulatedMagneticFieldGrid.html", null ],
        [ "PeriodicMagneticField", "classcrpropa_1_1PeriodicMagneticField.html", null ],
        [ "PshirkovField", "classcrpropa_1_1PshirkovField.html", null ],
        [ "TorroidalHaloField", "classcrpropa_1_1TorroidalHaloField.html", null ],
        [ "UniformMagneticField", "classcrpropa_1_1UniformMagneticField.html", null ]
      ] ],
      [ "Module", "classcrpropa_1_1Module.html", [
        [ "AbstractCondition", "classcrpropa_1_1AbstractCondition.html", [
          [ "CubicBoundary", "classcrpropa_1_1CubicBoundary.html", null ],
          [ "EllipsoidalBoundary", "classcrpropa_1_1EllipsoidalBoundary.html", null ],
          [ "MaximumTrajectoryLength", "classcrpropa_1_1MaximumTrajectoryLength.html", null ],
          [ "MinimumEnergy", "classcrpropa_1_1MinimumEnergy.html", null ],
          [ "MinimumRedshift", "classcrpropa_1_1MinimumRedshift.html", null ],
          [ "ParticleFilter", "classcrpropa_1_1ParticleFilter.html", null ],
          [ "SphericalBoundary", "classcrpropa_1_1SphericalBoundary.html", null ]
        ] ],
        [ "CRPropa2EventOutput1D", "classcrpropa_1_1CRPropa2EventOutput1D.html", null ],
        [ "CRPropa2EventOutput3D", "classcrpropa_1_1CRPropa2EventOutput3D.html", null ],
        [ "CRPropa2TrajectoryOutput1D", "classcrpropa_1_1CRPropa2TrajectoryOutput1D.html", null ],
        [ "CRPropa2TrajectoryOutput3D", "classcrpropa_1_1CRPropa2TrajectoryOutput3D.html", null ],
        [ "ElectronPairProduction", "classcrpropa_1_1ElectronPairProduction.html", null ],
        [ "EMDoublePairProduction", "classcrpropa_1_1EMDoublePairProduction.html", null ],
        [ "EMInverseComptonScattering", "classcrpropa_1_1EMInverseComptonScattering.html", null ],
        [ "EMPairProduction", "classcrpropa_1_1EMPairProduction.html", null ],
        [ "EMTripletPairProduction", "classcrpropa_1_1EMTripletPairProduction.html", null ],
        [ "FutureRedshift", "classcrpropa_1_1FutureRedshift.html", null ],
        [ "ModuleList", "classcrpropa_1_1ModuleList.html", null ],
        [ "ModuleListRunner", "classcrpropa_1_1ModuleListRunner.html", null ],
        [ "NuclearDecay", "classcrpropa_1_1NuclearDecay.html", null ],
        [ "Observer", "classcrpropa_1_1Observer.html", null ],
        [ "Output", "classcrpropa_1_1Output.html", [
          [ "TextOutput", "classcrpropa_1_1TextOutput.html", null ]
        ] ],
        [ "PerformanceModule", "classcrpropa_1_1PerformanceModule.html", null ],
        [ "PeriodicBox", "classcrpropa_1_1PeriodicBox.html", null ],
        [ "PhotoDisintegration", "classcrpropa_1_1PhotoDisintegration.html", null ],
        [ "PhotonDINT", "classcrpropa_1_1PhotonDINT.html", null ],
        [ "PhotonDINT1D", "classcrpropa_1_1PhotonDINT1D.html", null ],
        [ "PhotonEleCa", "classcrpropa_1_1PhotonEleCa.html", null ],
        [ "PhotonOutput1D", "classcrpropa_1_1PhotonOutput1D.html", null ],
        [ "PhotoPionProduction", "classcrpropa_1_1PhotoPionProduction.html", null ],
        [ "PropagationCK", "classcrpropa_1_1PropagationCK.html", null ],
        [ "Redshift", "classcrpropa_1_1Redshift.html", null ],
        [ "ReflectiveBox", "classcrpropa_1_1ReflectiveBox.html", null ],
        [ "ShellOutput", "classcrpropa_1_1ShellOutput.html", null ],
        [ "ShellOutput1D", "classcrpropa_1_1ShellOutput1D.html", null ],
        [ "ShellPropertyOutput", "classcrpropa_1_1ShellPropertyOutput.html", null ],
        [ "SimplePropagation", "classcrpropa_1_1SimplePropagation.html", null ]
      ] ],
      [ "ObserverFeature", "classcrpropa_1_1ObserverFeature.html", [
        [ "ObserverDetectAll", "classcrpropa_1_1ObserverDetectAll.html", null ],
        [ "ObserverElectronVeto", "classcrpropa_1_1ObserverElectronVeto.html", null ],
        [ "ObserverInactiveVeto", "classcrpropa_1_1ObserverInactiveVeto.html", null ],
        [ "ObserverLargeSphere", "classcrpropa_1_1ObserverLargeSphere.html", null ],
        [ "ObserverNeutrinoVeto", "classcrpropa_1_1ObserverNeutrinoVeto.html", null ],
        [ "ObserverNucleusVeto", "classcrpropa_1_1ObserverNucleusVeto.html", null ],
        [ "ObserverPhotonVeto", "classcrpropa_1_1ObserverPhotonVeto.html", null ],
        [ "ObserverPoint", "classcrpropa_1_1ObserverPoint.html", null ],
        [ "ObserverRedshiftWindow", "classcrpropa_1_1ObserverRedshiftWindow.html", null ],
        [ "ObserverSmallSphere", "classcrpropa_1_1ObserverSmallSphere.html", null ],
        [ "ObserverTracking", "classcrpropa_1_1ObserverTracking.html", null ]
      ] ],
      [ "SourceFeature", "classcrpropa_1_1SourceFeature.html", [
        [ "SourceComposition", "classcrpropa_1_1SourceComposition.html", null ],
        [ "SourceDensityGrid", "classcrpropa_1_1SourceDensityGrid.html", null ],
        [ "SourceDensityGrid1D", "classcrpropa_1_1SourceDensityGrid1D.html", null ],
        [ "SourceDirection", "classcrpropa_1_1SourceDirection.html", null ],
        [ "SourceEmissionCone", "classcrpropa_1_1SourceEmissionCone.html", null ],
        [ "SourceEnergy", "classcrpropa_1_1SourceEnergy.html", null ],
        [ "SourceIsotropicEmission", "classcrpropa_1_1SourceIsotropicEmission.html", null ],
        [ "SourceMultipleParticleTypes", "classcrpropa_1_1SourceMultipleParticleTypes.html", null ],
        [ "SourceMultiplePositions", "classcrpropa_1_1SourceMultiplePositions.html", null ],
        [ "SourceParticleType", "classcrpropa_1_1SourceParticleType.html", null ],
        [ "SourcePosition", "classcrpropa_1_1SourcePosition.html", null ],
        [ "SourcePowerLawSpectrum", "classcrpropa_1_1SourcePowerLawSpectrum.html", null ],
        [ "SourceRedshift", "classcrpropa_1_1SourceRedshift.html", null ],
        [ "SourceRedshift1D", "classcrpropa_1_1SourceRedshift1D.html", null ],
        [ "SourceRedshiftEvolution", "classcrpropa_1_1SourceRedshiftEvolution.html", null ],
        [ "SourceUniform1D", "classcrpropa_1_1SourceUniform1D.html", null ],
        [ "SourceUniformBox", "classcrpropa_1_1SourceUniformBox.html", null ],
        [ "SourceUniformRedshift", "classcrpropa_1_1SourceUniformRedshift.html", null ],
        [ "SourceUniformShell", "classcrpropa_1_1SourceUniformShell.html", null ],
        [ "SourceUniformSphere", "classcrpropa_1_1SourceUniformSphere.html", null ]
      ] ],
      [ "SourceInterface", "classcrpropa_1_1SourceInterface.html", [
        [ "Source", "classcrpropa_1_1Source.html", null ],
        [ "SourceList", "classcrpropa_1_1SourceList.html", null ]
      ] ]
    ] ],
    [ "Vector3< T >", "classcrpropa_1_1Vector3.html", null ],
    [ "Vector3< double >", "classcrpropa_1_1Vector3.html", null ],
    [ "XmlExecute", "classcrpropa_1_1XmlExecute.html", null ],
    [ "PropagationCK::Y", "classcrpropa_1_1PropagationCK_1_1Y.html", null ]
];